AWSTemplateFormatVersion: "2010-09-09"
Description: VPC for nagiyu in development

Resources:
  NagiyuVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: dev-nagiyu-vpc

  NagiyuInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: dev-nagiyu-igw

  NagiyuVPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref NagiyuVPC
      InternetGatewayId: !Ref NagiyuInternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref NagiyuVPC
      Tags:
        - Key: Name
          Value: dev-nagiyu-public-rt

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: NagiyuVPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref NagiyuInternetGateway

  NMARegisterBatchSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref NagiyuVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: dev-niconico-mylist-assistant-register-batch-subnet-1
        - Key: Project
          Value: dev-niconico-mylist-assistant

  NMARegisterBatchSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref NagiyuVPC
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: dev-niconico-mylist-assistant-register-batch-subnet-2
        - Key: Project
          Value: dev-niconico-mylist-assistant

  CodecConverterBatchSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref NagiyuVPC
      CidrBlock: 10.0.3.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: dev-codec-converter-batch-subnet-1
        - Key: Project
          Value: dev-codec-converter

  CodecConverterBatchSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref NagiyuVPC
      CidrBlock: 10.0.4.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: dev-codec-converter-batch-subnet-2
        - Key: Project
          Value: dev-codec-converter

  Subnet1RouteAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref NMARegisterBatchSubnet1
      RouteTableId: !Ref PublicRouteTable

  Subnet2RouteAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref NMARegisterBatchSubnet2
      RouteTableId: !Ref PublicRouteTable

  CodecConverterBatchSubnet1RouteAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref CodecConverterBatchSubnet1
      RouteTableId: !Ref PublicRouteTable

  CodecConverterBatchSubnet2RouteAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref CodecConverterBatchSubnet2
      RouteTableId: !Ref PublicRouteTable

Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref NagiyuVPC
  Subnet1Id:
    Description: NMA Register Batch Subnet 1 ID
    Value: !Ref NMARegisterBatchSubnet1
  Subnet2Id:
    Description: NMA Register Batch Subnet 2 ID
    Value: !Ref NMARegisterBatchSubnet2
  CodecConverterBatchSubnet1Id:
    Description: Codec Converter Batch Subnet 1 ID
    Value: !Ref CodecConverterBatchSubnet1
  CodecConverterBatchSubnet2Id:
    Description: Codec Converter Batch Subnet 2 ID
    Value: !Ref CodecConverterBatchSubnet2
