AWSTemplateFormatVersion: "2010-09-09"
Description: IAM User and Policy for GitHub Actions

Resources:
  GitHubActionsUser:
    Type: AWS::IAM::User
    Properties:
      UserName: github-actions-user
      Path: /

  GitHubActionsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: github-actions
      Users:
        - !Ref GitHubActionsUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:*
            Resource: "*"
          - Effect: Allow
            Action:
              - iam:*
            Resource: "*"
